<a href="https://colab.research.google.com/github/F4078/python_project/blob/main/Assignment_01_Student_(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

___

<a href="https://lms.clarusway.com/course/view.php?id=37"><img align="center" src="https://i.ibb.co/6Z5pQxD/lmss.png" alt="Open in Clarusway LMS" width="70" height="200" title="Open Clarusway Learning Management Sytem"></a>

<a href="https://github.com/clarusway/DS-DE-0322-Students/blob/main/3-%20Classes%26Labs/3-DVwPY/DVwPy_S06_Capstone_Project%20(Bike%20Store%20Sharing).ipynb"><img align="left" src="https://i.ibb.co/n3HWyQX/github-logo.png" alt="Open in Clarusway GitHub" width="100" height="150" title="Open and Execute in Clarusway GitHub Repository"></a>

<a href="https://nbviewer.org/github/4dsolutions/clarusway_data_analysis/blob/main/DVwPY_S6/6-DVwPy%20Capstone%20%28Bike%20Store%20Sharing%29.ipynb"><img align="right" src="https://i.ibb.co/48wtV8c/nbviewer-badge.png" alt="Open in nbviewer" width="130" height="200" title="Open and Execute in nbviewer"></a><br/>
___

<a href="https://clarusway.com/"><img align="center" src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" alt="CLRSWY" width="450" height="200" title="Welcome to Place Where You can Reinvent Yourself"></a><br/>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:120%; text-align:center; border-radius:10px 10px;">Way to Reinvent Yourself</p>

<p style="text-align: center;"><img src="https://i.ibb.co/99DQ3TY/DS-Courses.png" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:200%; text-align:center; border-radius:10px 10px;">Data Analysis with Python</p>

![Image_Assignment](https://i.ibb.co/cY9HhF7/bnote-assignment.gif)

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#4d77cf; font-size:200%; text-align:center; border-radius:10px 10px;">Assignment 01 (NumPy & Pandas Basics)</p>

<a id="toc"></a>

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Content</p>

* [NUMPY SECTION](#0)
* [PANDAS SECTION](#1)


**In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!**

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Numpy Section</p>

<a id="0"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### 1. Import NumPy Library.

In [2]:
# YOUR CODE IS HERE
import numpy as np 


### 2. Create an array from my_list = [5, 10, 15, 20, 25]

In [3]:
from numpy.core.multiarray import may_share_memory
# YOUR CODE IS HERE
my_list = [5, 10, 15, 20, 25]
my_arr = np.array(my_list)
my_arr



array([ 5, 10, 15, 20, 25])

### 3. Generate an array of 5x5 with zeros. 

In [4]:
# YOUR CODE IS HERE
np.zeros((5,5))


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### 4. Generate an array of 4x4 with ones and assign data type as int.

In [5]:
# YOUR CODE IS HERE
np.ones((4,4), dtype = int )

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

### 5. Make all the values of the array above with the value of 7.

In [6]:
# YOUR CODE IS HERE
np.linspace(7, 7, 16, dtype = int).reshape(4,4)


array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 6. Create the previous array above by full() method.

In [7]:
# YOUR CODE IS HERE
np.full((4, 4), 7)


array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 7. Create an array of even integers from 2 to 16 (inclusive). 

In [8]:
# YOUR CODE IS HERE
np.arange(2, 17, 2)


array([ 2,  4,  6,  8, 10, 12, 14, 16])

### 8. Create a 5x5 matrix with the values between 0 to 25 (exclusive).

In [9]:
# YOUR CODE IS HERE
np.arange(0, 25).reshape(5,5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### 9. Create a 5x5 matrix with the values between 0 to 25 (exclusive) using linspace method.

In [10]:
# YOUR CODE IS HERE
np.linspace(0, 25, num = 25, endpoint = False, dtype = int).reshape(5,5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### 10. Create randomly 5 numbers with numpy.

In [11]:
# YOUR CODE IS HERE
np.random.randint(0, 20, 5)


array([10,  4,  4, 16,  3])

### 11. Create an array of 5*5 shape and fills it with random values as per the standard normal distribution.

In [12]:
# YOUR CODE IS HERE
np.random.randn(5,5)


array([[ 0.19743567,  0.25088827, -0.22627892,  0.96368207,  0.8183597 ],
       [ 0.13856576,  0.75050709, -2.66755083, -0.48588573, -0.296801  ],
       [ 1.22733365, -0.13529264, -1.68398271,  0.75380405, -0.95841187],
       [-0.87210553,  0.57405852, -0.86075367,  0.33191348, -0.06112296],
       [-0.81370401,  0.07340726, -0.4851502 ,  0.0796581 , -3.14372986]])

### 12. Create a 3*4 array of random int numbers between 20 and 50.

In [13]:
# YOUR CODE IS HERE
np.random.randint(20, 50, size = (3,4))


array([[34, 44, 25, 29],
       [38, 28, 37, 47],
       [25, 20, 24, 32]])

### 13. Create an array named "ranarr"consisting of randomly 48 numbers and reshape this array with the shape of 6x8 in different ways.

In [14]:
# YOUR CODE IS HERE
ranarr = np.random.randint(0, 100, 48)
ranarr

array([75, 31, 58, 36, 23, 99, 18, 22, 77, 84,  2, 74, 60, 65, 65, 98, 14,
       41, 26, 63, 62, 86, 40, 26, 28, 63, 78, 25,  5, 47, 80, 41, 78,  6,
       89, 87, 57, 13, 84, 95, 43, 19, 42, 82, 21, 81,  0, 86])

In [15]:
# YOUR CODE IS HERE (RESHAPING WITH NUM)
np.reshape(ranarr, (6,8))


array([[75, 31, 58, 36, 23, 99, 18, 22],
       [77, 84,  2, 74, 60, 65, 65, 98],
       [14, 41, 26, 63, 62, 86, 40, 26],
       [28, 63, 78, 25,  5, 47, 80, 41],
       [78,  6, 89, 87, 57, 13, 84, 95],
       [43, 19, 42, 82, 21, 81,  0, 86]])

In [16]:
# YOUR CODE IS HERE (RESHAPING WITH -1)
np.random.randint(10, size = (6,8))


array([[5, 1, 4, 6, 2, 0, 9, 2],
       [4, 2, 9, 0, 7, 2, 6, 8],
       [6, 9, 7, 1, 4, 6, 1, 6],
       [0, 6, 3, 3, 4, 8, 0, 9],
       [2, 9, 3, 0, 6, 6, 9, 3],
       [3, 7, 9, 7, 8, 1, 5, 1]])

In [17]:
# YOUR CODE IS HERE (RESHAPING WITH -2)
ranarr.reshape(6,8)

array([[75, 31, 58, 36, 23, 99, 18, 22],
       [77, 84,  2, 74, 60, 65, 65, 98],
       [14, 41, 26, 63, 62, 86, 40, 26],
       [28, 63, 78, 25,  5, 47, 80, 41],
       [78,  6, 89, 87, 57, 13, 84, 95],
       [43, 19, 42, 82, 21, 81,  0, 86]])

## Numpy Indexing and Selection

### Create an array named "mat" in accordence with the desired output below.

In [18]:
# YOUR CODE IS HERE 
mat = np.arange(1, 17).reshape(4, 4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### 14. Using the array above, write a code that reproduces the desired output shown below.<br>

In [19]:
# YOUR CODE IS HERE 
mat[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

### 15. Get the 1st column (index number 0) of the array above.

In [20]:
# YOUR CODE IS HERE 
mat[:,[0]].T

array([[ 1,  5,  9, 13]])

### 16. Get the values in 2nd row (index number 1) for every 2 step.

In [21]:
# YOUR CODE IS HERE 
mat[(1, 1), (0, 2)]

array([5, 7])

### 17.Assign 77 to every cell in 3rd column.

In [22]:
# YOUR CODE IS HERE 
mat[:,2:3] = 77
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

### 18. (a) Take 2nd row (index number 1) and 1st column (index number 0) , (b) 4th row (index number 3) and 3rd column (index number 2) .

In [23]:
# YOUR CODE IS HERE 
mat[(1,1) , (0,2)]

array([ 5, 77])

### 19. Take between 2nd and last row with step 2 and between 1st and last column with step 2.

In [24]:
# YOUR CODE IS HERE 
mat[1::2,0:3:2]

array([[ 5, 77],
       [13, 77]])

## NumPy Operations

### 20. Get the sum of values smaller than 10 and values bigger than 12 in "mat".

In [25]:
# LET US REMEMBER OUR ARRAY OF "mat" 

# YOUR CODE IS HERE 
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [26]:
# LET US FIND THE VALUES SMALLER THAN 10 IN "mat" 

# YOUR CODE IS HERE 
mat[mat < 10]


array([1, 2, 4, 5, 6, 8, 9])

In [27]:
# LET US FIND THE VALUES BIGGER THAN 12 IN "mat" 

# YOUR CODE IS HERE 
mat[mat > 12]


array([77, 77, 77, 13, 14, 77, 16])

In [28]:
# LET US SUM THE VALUES SMALLER THAN 10 AND BIGGER THAN 12 IN "mat" 
# YOUR CODE IS HERE 
mat[mat < 10] + mat[mat>12]

array([78, 79, 81, 18, 20, 85, 25])

### 21. Get the standard deviation (std) of the result above.

In [29]:
# YOUR CODE IS HERE 
np.std(mat)


30.004166377354995

### 22. Get the sum of the 2nd column in the original "mat".

In [30]:
# LET US REMEMBER OUR ARRAY OF "mat" 

# YOUR CODE IS HERE 
mat


array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [31]:
# LET OBTAIN THE ORIGINAL ARRAY OF "mat" 

# YOUR CODE IS HERE 
mat = np.arange(1, 17).reshape(4, 4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [32]:
# YOUR CODE IS HERE 
sum(mat[:, [1]])


array([32])

### 23. Get the median, mean and std of 3rd column in "mat".

In [33]:
# LET US REMEMBER OUR ARRAY OF "mat" 

# YOUR CODE IS HERE 
mat = np.arange(1, 17).reshape(4, 4)
mat


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [34]:
# LET US ASSIGN THE COLUMN WE ARE INTERESTED IN TO A VARIABLE 

# YOUR CODE IS HERE 
colm3 = mat[:, [2]]
colm3


array([[ 3],
       [ 7],
       [11],
       [15]])

In [35]:
# WHAT IF WE ARE INTERESTED IN THE 3RD ROW? 

# YOUR CODE IS HERE 
row3 = mat[[2], :]
row3

array([[ 9, 10, 11, 12]])

In [36]:
# LET US GET MEDIAN VALUE 

# YOUR CODE IS HERE 
print(np.median(colm3))
np.median(row3)

9.0


10.5

In [37]:
# LET US GET MEAN VALUE 

# YOUR CODE IS HERE 
print(np.mean(colm3))
np.mean(row3)

9.0


10.5

In [38]:
# LET US GET STANDART DEVIATION (std) VALUE 

# YOUR CODE IS HERE 
print(np.std(colm3))
np.std(row3)

4.47213595499958


1.118033988749895

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Pandas Section</p>

<a id="1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### Import Pandas Library

In [39]:
# YOUR CODE IS HERE 
import pandas as pd 


### Read Salaries.csv and take a look at the first 5 rows, df info and df statistical measurements.*

In [40]:
# LET US READ Salaries.csv 

# YOUR CODE IS HERE 



In [41]:
# LET US LOOK AT THE FIRST 5 ROWS 

# YOUR CODE IS HERE 
df = pd.read_csv("/Salaries.csv")
df.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

Desired Output:

![image.png](https://i.ibb.co/6BTmGX8/assignment1a.png)

In [42]:
# LET US GET A SAMPLE 

# YOUR CODE IS HERE 
df.sample()


Id     EmployeeName                    JobTitle  BasePay  \
148435  148436  Rebecca Woodson  BdComm Mbr, Grp2,M=$25/Mtg    175.0   

        OvertimePay  OtherPay  Benefits  TotalPay  TotalPayBenefits  Year  \
148435          0.0       0.0     41.59     175.0            216.59  2014   

        Notes         Agency  Status  
148435    NaN  San Francisco     NaN

Desired Output (WATCH OUT! Your output may NOT be the same as the one):

![image.png](https://i.ibb.co/mcsCxxC/assignment1b.png)

In [43]:
# YOUR CODE IS HERE 
print(type(df))
df.shape

<class 'pandas.core.frame.DataFrame'>


(148654, 13)

In [44]:
# LET US GET SOME DESCRIPTIVE MEASUREMENTS  

# YOUR CODE IS HERE 
df.describe()


Id        BasePay    OvertimePay       OtherPay  \
count  148654.000000  148045.000000  148650.000000  148650.000000   
mean    74327.500000   66325.448840    5066.059886    3648.767297   
std     42912.857795   42764.635495   11454.380559    8056.601866   
min         1.000000    -166.010000      -0.010000   -7058.590000   
25%     37164.250000   33588.200000       0.000000       0.000000   
50%     74327.500000   65007.450000       0.000000     811.270000   
75%    111490.750000   94691.050000    4658.175000    4236.065000   
max    148654.000000  319275.010000  245131.880000  400184.250000   

            Benefits       TotalPay  TotalPayBenefits           Year  Notes  \
count  112491.000000  148654.000000     148654.000000  148654.000000    0.0   
mean    25007.893151   74768.321972      93692.554811    2012.522643    NaN   
std     15402.215858   50517.005274      62793.533483       1.117538    NaN   
min       -33.890000    -618.130000       -618.130000    2011.000000    NaN   
25%     11535.395000   36168.995000      44065.650000    2012.000000    NaN   
50%     28628.620000   71426.610000      92404.090000    2013.000000    NaN   
75%     35566.855000  105839.135000     132876.450000    2014.000000    NaN   
max     96570.660000  567595.430000     567595.430000    2014.000000    NaN   

       Status  
count     0.0  
mean      NaN  
std       NaN  
min       NaN  
25%       NaN  
50%       NaN  
75%       NaN  
max       NaN

Desired Output:

![image.png](https://i.ibb.co/ftMP67H/assignmnet1c.png)

### How many different year values are there?

In [45]:

# YOUR CODE IS HERE 
df.Year.value_counts()



2014    38123
2013    37606
2012    36766
2011    36159
Name: Year, dtype: int64

In [46]:
# LET US FIND THE NUMBER OF UNIQUE VALUES IN THE COLUMN OF "Year"

# YOUR CODE IS HERE 
df.Year.nunique()


4

In [47]:
# LET US FIND THE UNIQUE VALUES IN THE COLUMN OF "Year"

# YOUR CODE IS HERE 
df.Year.unique()


array([2011, 2012, 2013, 2014])

### Print out max and avg values in the column of "Totalpay".

In [48]:
# LET US FIND THE MAXIMUM TOTALPAY

# YOUR CODE IS HERE 
df["TotalPay"].max()


567595.43

In [49]:
# LET US FIND THE AVERAGE TOTALPAY

# YOUR CODE IS HERE 
df["TotalPay"].mean()


74768.32197169267

### How many records in the TotalPay column are there bigger than avg TotalPay?

In [50]:
# YOUR CODE IS HERE 
df[df["TotalPay"].mean() < df["TotalPay"]]


Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
135701  135702    Christina S Jee   
135778  135779  Mary Ann T Abille   
135847  135848   Emilda E Reinosa   
135853  135854      David G Evans   
136063  136064         Nicole Joe   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
135701                              Nurse Practitioner   70635.61   
135778                                   Special Nurse   60889.34   
135847                                   Special Nurse   76305.74   
135853                                   Special Nurse   71178.15   
136063                                   Special Nurse   61276.59   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
135701         0.00    6550.41    771.88   77186.02          77957.90  2014   
135778      6815.67    9041.21    767.47   76746.22          77513.69  2014   
135847         0.00       0.00    763.08   76305.74          77068.82  2014   
135853      2748.15    2354.40    762.81   76280.70          77043.51  2014   
136063      8538.44    5078.67    748.95   74893.70          75642.65  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
1         NaN  San Francisco     NaN  
2         NaN  San Francisco     NaN  
3         NaN  San Francisco     NaN  
4         NaN  San Francisco     NaN  
...       ...            ...     ...  
135701    NaN  San Francisco     NaN  
135778    NaN  San Francisco     NaN  
135847    NaN  San Francisco     NaN  
135853    NaN  San Francisco     NaN  
136063    NaN  San Francisco     NaN  

[69489 rows x 13 columns]

Desired Output:

![image.png](https://i.ibb.co/nj84FbZ/assignment1d.png)

In [51]:
# YOUR CODE IS HERE 
df[df["TotalPay"].mean() < df["TotalPay"]]["TotalPay"].count()


69489

### How much does ALBERT PARDINI make money (including benefits)?

In [52]:
# YOUR CODE IS HERE 
df.loc[[2],["TotalPayBenefits"]]


TotalPayBenefits
2         335279.91

### Who is the lowest paid person?

In [53]:
# YOUR CODE IS HERE 
df[df.TotalPayBenefits == df.TotalPayBenefits.min()]["EmployeeName"]
#df.sort_values("TotalPayBenefits")["EmployeeName"].head(1)

148653    Joe Lopez
Name: EmployeeName, dtype: object

In [54]:
df.sort_values("TotalPayBenefits")["EmployeeName"].head(1)

148653    Joe Lopez
Name: EmployeeName, dtype: object

### What are the unique Jobs in dataset?

In [55]:
# YOUR CODE IS HERE 
df_jop = df["JobTitle"].unique()
df_jop

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)




### List the top 3 least common Jobs in the dataset.

In [56]:
# YOUR CODE IS HERE 
df["JobTitle"].value_counts().tail(3)

COURT COMPUTER FACILITIES COORDINATOR             1
AUTOMOTIVE BODY AND FENDER WORKER SUPERVISOR I    1
VICTIM & WITNESS TECHNICIAN                       1
Name: JobTitle, dtype: int64

### How many people earned more than avg in 2012?

In [57]:
# YOUR CODE IS HERE 
df[(df["TotalPayBenefits"] > df["TotalPayBenefits"].mean()) & (df["Year"] == 2012)]["Id"].count()


20366

In [58]:
df.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

### How many people have a title of Manager in their jobs?

In [59]:
# USE APPLY FUNCTION FOR THIS QUESTION!

# YOUR CODE IS HERE 
len(df[df.JobTitle.apply(lambda x : True if "manager" in x.lower() else False )])


4110

### Take Id, EmployeeName, JobTitle, TotalPay and TotalPayBenefits columns with iloc and assign them as sal_new dataframe.

In [60]:
# YOUR CODE IS HERE 
sal_new = df.iloc[:,[0,1,2,7,8]]
sal_new

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle   TotalPay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  567595.43   
1                      CAPTAIN III (POLICE DEPARTMENT)  538909.28   
2                      CAPTAIN III (POLICE DEPARTMENT)  335279.91   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC  332343.61   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  326373.19   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided       0.00   
148651                                    Not provided       0.00   
148652                                    Not provided       0.00   
148653                      Counselor, Log Cabin Ranch    -618.13   

        TotalPayBenefits  
0              567595.43  
1              538909.28  
2              335279.91  
3              332343.61  
4              326373.19  
...                  ...  
148649              0.00  
148650              0.00  
148651              0.00  
148652              0.00  
148653           -618.13  

[148654 rows x 5 columns]

Desired Output:

![image.png](https://i.ibb.co/ZgFCbPm/assignment1e.png)

### Take the columns betweeen EmployeeName and TotalPayBenefits with loc and assign them as sal_new df.

In [61]:
# YOUR CODE IS HERE 
sal_new = df.loc[:, "EmployeeName" : "TotalPayBenefits"]
sal_new 

EmployeeName                                        JobTitle  \
0          NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1            GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2          ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3       CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4         PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   
...                   ...                                             ...   
148649      Roy I Tillery                                       Custodian   
148650       Not provided                                    Not provided   
148651       Not provided                                    Not provided   
148652       Not provided                                    Not provided   
148653          Joe Lopez                      Counselor, Log Cabin Ranch   

          BasePay  OvertimePay   OtherPay  Benefits   TotalPay  \
0       167411.18         0.00  400184.25       NaN  567595.43   
1       155966.02    245131.88  137811.38       NaN  538909.28   
2       212739.13    106088.18   16452.60       NaN  335279.91   
3        77916.00     56120.71  198306.90       NaN  332343.61   
4       134401.60      9737.00  182234.59       NaN  326373.19   
...           ...          ...        ...       ...        ...   
148649       0.00         0.00       0.00       0.0       0.00   
148650        NaN          NaN        NaN       NaN       0.00   
148651        NaN          NaN        NaN       NaN       0.00   
148652        NaN          NaN        NaN       NaN       0.00   
148653       0.00         0.00    -618.13       0.0    -618.13   

        TotalPayBenefits  
0              567595.43  
1              538909.28  
2              335279.91  
3              332343.61  
4              326373.19  
...                  ...  
148649              0.00  
148650              0.00  
148651              0.00  
148652              0.00  
148653           -618.13  

[148654 rows x 8 columns]

Desired Output:

![image.png](https://i.ibb.co/s2CYS7H/assignment1f.png)

### Print out the names of the employees who earn more than min but less than avg.

In [62]:
# YOUR CODE IS HERE 
df[(df.TotalPayBenefits > df.TotalPayBenefits.min()) & (df.TotalPayBenefits < df.TotalPayBenefits.mean())]\
[["EmployeeName", "TotalPayBenefits"]]


EmployeeName  TotalPayBenefits
10806          KWE LEE          93691.15
10807   MIGUEL CARO JR          93682.74
10808    JOANNE MORRIS          93680.53
10809    LAYLA WELBORN          93676.88
10810          LE BANH          93675.39
...                ...               ...
148648     Leon Walker              0.00
148649   Roy I Tillery              0.00
148650    Not provided              0.00
148651    Not provided              0.00
148652    Not provided              0.00

[75649 rows x 2 columns]

Desired Output:

![image.png](https://i.ibb.co/mtNB2TX/assignment1g.png)

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

________